In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df = pd.read_csv(r'/content/heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
df.describe()

age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

In [4]:
endog = df['target'].head(4)

In [5]:
exog =  df[['slope','sex','age']].head(4)

In [6]:
print(exog)

   slope  sex  age
0      0    1   63
1      0    1   37
2      2    0   41
3      2    1   56


In [7]:
X=exog.to_numpy()

In [8]:
Y= endog.to_numpy()

In [9]:
print(X)

[[ 0  1 63]
 [ 0  1 37]
 [ 2  0 41]
 [ 2  1 56]]


In [10]:
from numpy import array
from numpy import mean

In [11]:
from numpy import cov
from numpy.linalg import eig

In [12]:
M = mean(X.T, axis=1)

In [13]:
print(M)

[ 1.    0.75 49.25]


In [14]:
C= X-M

In [15]:
print(C)

[[ -1.     0.25  13.75]
 [ -1.     0.25 -12.25]
 [  1.    -0.75  -8.25]
 [  1.     0.25   6.75]]


In [16]:
V = cov(C.T)

In [17]:
print(V)


[[  1.33333333  -0.33333333  -1.        ]
 [ -0.33333333   0.25         2.75      ]
 [ -1.           2.75       150.91666667]]


In [18]:
values, vectors = eig(V)

In [19]:
print(vectors)

[[-0.0067221   0.96765856 -0.252174  ]
 [ 0.01825673 -0.2520189  -0.96755008]
 [ 0.99981073  0.01110784  0.01597219]]


In [20]:
print(values)

[1.50973606e+02 1.40866824e+00 1.17726215e-01]


In [21]:
P = vectors.T.dot(C.T)

In [22]:
print(P.T)

[[ 13.75868388  -0.87793052   0.22990404]
 [-12.23639522  -1.16673429  -0.1853728 ]
 [ -8.26885321   1.06503308   0.34171803]
 [  6.74656455   0.97963174  -0.38624926]]


In [23]:
from sklearn.decomposition import PCA

In [24]:
pca = PCA(n_components=1)

In [25]:
principalComponents = pca.fit_transform(X)

In [26]:
principalDf = pd.DataFrame(data = principalComponents,columns = ['principal component 1'])

In [27]:
exog1 = sm.add_constant(principalDf[['principal component 1']])

In [28]:
print(exog1)

   const  principal component 1
0    1.0              13.758684
1    1.0             -12.236395
2    1.0              -8.268853
3    1.0               6.746565


In [29]:
from sklearn import linear_model

In [30]:
lm = linear_model.LinearRegression()

In [31]:
model = lm.fit(exog1,endog)

In [32]:
lm.coef_

array([0., 0.])

In [34]:
lm.intercept_

1.0

In [35]:
def RSE(y_true, y_predicted):
    
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [36]:
ypred =lm.predict(exog1)

In [37]:
re = RSE(endog,ypred)
print(re)

0.0
